# Generated by Django 4.0.3 on 2022-03-16 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_room_description_alter_category_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='price',
            field=models.IntegerField(default=100),
            preserve_default=False,
        ),
    ]
