# Generated by Django 4.0.3 on 2022-03-16 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_room_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='slug',
            field=models.SlugField(default='room'),
            preserve_default=False,
        ),
    ]
