# Generated by Django 4.0.3 on 2022-03-16 22:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_room_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='image',
            field=models.FileField(blank=True, upload_to=''),
        ),
        migrations.CreateModel(
            name='RoomImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.FileField(upload_to='images/')),
                ('room', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='app.room')),
            ],
        ),
    ]
