# Generated by Django 4.0.3 on 2022-03-22 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_booking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='category',
            field=models.CharField(choices=[('AC', 'AC'), ('DEL', 'DELUXE'), ('BUS', 'BUSINESS'), ('STA', 'STANDARD'), ('EXE', 'EXECUTIVE'), ('KN', 'KING'), ('PNT', 'PENTHOUSE')], max_length=3),
        ),
    ]
